name: Web App Deployment Demo

# Using workload identity federation to authenticate to Azure
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

env:
    resourceGroup: demo-resource-gp

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Bicep File
        uses: actions/checkout@v3

      # Login to Azure using Workflow Identity Federation
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: 'Retrieve the service principal id for the application'
        uses: azure/CLI@v1 
        id: site-creds
        with:
          inlineScript: |
            spId=$(az ad sp list --filter "appId eq '$appId'" --query [].id --output tsv)
            # Mask the principal id so it is not shown in workflow logs
            APP_SP_ID="$spId"
            echo "::add-mask::$APP_SP_ID"
            echo APP_SP_ID=$APP_SP_ID >> $GITHUB_ENV

      # Update the bicep param file with the correct application
      # service principal id
      - name: 'Update Bicep Param File'
        run: |
          sed -i "s/<spId>/${{env.APP_SP_ID}}/g" webapp_deploy.bicepparam

      # Deploy Bicep
      - name: 'Deploy the Azure infrastructure using Bicep'
        uses: azure/arm-deploy@v1
        id: deploy_bicep
        with:
            scope: resourcegroup
            subscriptionId: ${{secrets.AZURE_SUBSCRIPTION_ID}}
            resourceGroupName: ${{env.resourceGroup}}
            template: ./webapp_deploy.bicep
            parameters: ./webapp_deploy.bicepparam
            deploymentName: webapp_deployment
